### ISSUE TITLE
Unmarshaling error in readMessages function

### ISSUE THREAD

**Issue by romainisnel** [romainisnel/hertz#19]
While testing the connect command (!j) when nobody was in a voice channel, a received event apparently contained a **boolean** as its **data (d)** payload.

```
panic: json: cannot unmarshal bool into Go struct field Payload.d of type map[string]interface {}

goroutine 102 [running]:
main.(*Bot).readMessages(0xc0000d4000)
	/Users/romain/Code/hertz/main.go:380 +0x1f0
created by main.(*Bot).init
	/Users/romain/Code/hertz/main.go:208 +0x152
```

A simple condition should be enough to avoid the error from happening.

**Comment by romainisnel** [comment]
This error is thrown when the program receives a payload with the Opcode 9 (Invalid Session). Giving the following payload.

```{"t":null,"s":null,"op":9,"d":false}```

As per why the Opcode 9 is received, this is an issue that should be handled independently.

**Comment by romainisnel** [comment]
The commit 9cb44724518da59579de6019637ac519f4481eea fixes the issue. This event was received because of a malformed payload that was sent to the gateway.

Sending malformed payloads is not allowed by the gateway, and will always result in it sending back Opcode 9 (Invalid Session).
